### ISSUE TITLE
What do I download?

### ISSUE THREAD

**Issue by ghost** [ibrahimAtespare/tetris-python#1]
What pygame do I download?

**Comment by ibrahimAtespare** [comment]
Pygame v1.9.3 and v1.9.6 both worked

**Comment by ghost** [comment]
Could you put a link to help us download those versions? I have no clue, I can download v2.0.6 through CMD, but other than that I don't know how to download it. Thank you in advance.

**Comment by ibrahimAtespare** [comment]
I couldn't find a proper way to install the 1.9.x versions of Pygame either, but I tried directly installing via cmd prompt and the latest version of Pygame worked out for me. I also added a short installation guide to the readme.
